### ISSUE TITLE
Error: Cannot find module 'mongodb'

### ISSUE THREAD

**Issue by chmaynard** [barrowclift/hacker-news-cleanser#4]
Found this in server.log:

```
Error: Cannot find module 'mongodb'
Require stack:
- /Users/Core/Develop/Projects/hacker-news-cleanser/server/MongoClient.js
- /Users/Core/Develop/Projects/hacker-news-cleanser/server/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/Core/Develop/Projects/hacker-news-cleanser/server/MongoClient.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Core/Develop/Projects/hacker-news-cleanser/server/MongoClient.js',
    '/Users/Core/Develop/Projects/hacker-news-cleanser/server/main.js'
  ]
}
```

**Comment by barrowclift** [comment]
Looks like dependencies weren't pulled. Generally, you'll want to execute `npm install` for any repositories you see a `package.json` for in the root, that typically means dependencies are managed with NPM and must be pulled, first.

**Comment by barrowclift** [comment]
I'll make a note to update the `INSTALL.md` directions to include an explicit step for downloading NPM dependencies.

**Comment by chmaynard** [comment]
Even after running 'npm install', I don't see mongodb in node_modules/.

**Comment by barrowclift** [comment]
That's unusual... did you get any error messages from `npm install`? For a quick sanity run, I deleted `node_modules` and re-ran `npm install`, and `mongodb` appeared as expected.

**Comment by barrowclift** [comment]
And did you ensure you executed `npm install` at the root of the project?

**Comment by chmaynard** [comment]
Try to replicate:

- Navigate to project root.
- Use admin/stop.sh to stop both the server and mongodb. 
- Delete node_modules/.
- Run npm install.

Result: 

- mongodb was installed as expected in node_modules/.

Problem solved, okay to close.
